In [1]:
# 1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

import numpy as np

a = np.array([[6, -8, 73, -110],
            [np.nan, -8, 0, 94]])

a = np.nan_to_num(a, nan=0)
print("NaN replace with 0:\n", a)

interchange_a = a.T
print("Rows and columns interchanged:\n", interchange_a)

NaN replace with 0:
 [[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
Rows and columns interchanged:
 [[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
# 2) Move axes of 3D array to new positions 

import numpy as np

a3d = np.arange(24).reshape(2, 3, 4)

print("Original shape:", a3d.shape)

new_a = np.moveaxis(a3d, 0, 2)

print("After moving axis:", new_a.shape)
print(new_a)

Original shape: (2, 3, 4)
After moving axis: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:
 # 3)Replace NaN values with average of columns

import numpy as np

a = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])

col_mean = np.nanmean(a, axis=0)

indx = np.where(np.isnan(a))
a[indx] = np.take(col_mean, indx[1])

print(a)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [4]:
# 4) Replace negative value with zero in numpy array using replace
import numpy as np

a = np.array([6, -8, 73, -110, 0, 94])

a = np.where(a < 0, 0, a)

print(a)

[ 6  0 73  0  0 94]
