In [ ]:
# 1)Combining a one and a two-dimensional NumPy Array
import numpy as np
a=np.array([1,2,3])
b=np.array([[4,5,6],[7,8,9]])
print("before combining:")
print("one dimensional array:")
print(a)
print("two dimensionl array:")
print(b)
print("after combining:")
a=a.reshape(1,3)
c=np.concatenate((a,b))
print(c)


before combining:
one dimensional array:
[1 2 3]
two dimensionl array:
[[4 5 6]
 [7 8 9]]
after combining:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 2)Flatten a 2d numpy array into 1d array 
a=np.array([[1,2,3],[7,8,9]])
b=a.flatten()
print("before flattening:")
print(a)
print("after flattening")
print(b)

before flattening:
[[1 2 3]
 [7 8 9]]
after flattening
[1 2 3 7 8 9]


In [ ]:
# 3)Reverse a numpy array
a=np.array([11,14,17,18,20])
b=np.array([[1,2,3],[4,5,6]])
print("before reversing")
print(a)
print("two dimensionl array:")
print(b)
print("after reversing")
print(a[::-1])
print("two dimensionl array:")
print(b[::-1])

before reversing
[11 14 17 18 20]
two dimensionl array:
[[1 2 3]
 [4 5 6]]
after reversing
[20 18 17 14 11]
two dimensionl array:
[[4 5 6]
 [1 2 3]]


In [ ]:
#4)Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy
arr=np.array([[56,87,90],[22,54,67]])
print("maximum value ",arr.max())
print("minimun value",arr.min())
row,column=arr.shape
print("number of rows",row)
print("number of columns",column)
print("all elements ")
for i in arr:
    for j in i:
        print(j,end=" ")
print()
print("specific element:", arr[1,1])
sum=0
for i in arr:
    for j in i:
        sum+=j
print("sum of vlues :",sum)
arr1=np.array([[1,2,3],[4,5,6]])
print("addition")
print(arr+arr1)
print("subtraction")
print(arr-arr1)
print("multiplication")
print(arr*arr1)
print("division")
print(arr/arr1)

maximum value  90
minimun value 22
number of rows 2
number of columns 3
all elements 
56 87 90 22 54 67 
specific element: 54
sum of vlues : 376
addition
[[57 89 93]
 [26 59 73]]
subtraction
[[55 85 87]
 [18 49 61]]
multiplication
[[ 56 174 270]
 [ 88 270 402]]
division
[[56.         43.5        30.        ]
 [ 5.5        10.8        11.16666667]]


In [ ]:
#5)Iterate 3D array using for loop and nditer
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("iterating using for loops:")
for i in c:
    for j in i:
        for k in j:
            print(k,end=" ")
print("\niteration using nditer:")
for x in np.nditer(c):
    print(x,end=" ")

iterating using for loops:
1 2 3 4 5 6 7 8 9 10 11 12 
iteration using nditer:
1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
#6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[6, 5, 4],
                 [3, 2, 1]])

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

avg = (arr1 + arr2) / 2
print("\nAverage of arrays:\n", avg)

mean_value = np.mean(avg)
print("\nMean:", mean_value)

median_value = np.median(avg)
print("Median:", median_value)

values, counts = np.unique(avg, return_counts=True)


mode = values[np.argmax(counts)]

print("Mode:", mode)



Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[6 5 4]
 [3 2 1]]

Average of arrays:
 [[3.5 3.5 3.5]
 [3.5 3.5 3.5]]

Mean: 3.5
Median: 3.5
Mode: 3.5
