In [2]:
#1-D to 2-D array
import numpy as np
a=np.array([1,2,3,4,5,6])
print("one dimensional array:")
print(a)
b=a.reshape(2,3)
print("Two dimensional array:")
print(b)


one dimensional array:
[1 2 3 4 5 6]
Two dimensional array:
[[1 2 3]
 [4 5 6]]


In [4]:
#array attributes
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array :")
print(c)
print(f"Shape: {c.shape}")
print(f"dimension : {c.ndim}")
print(f"Data type : {c.dtype}")
print(f"Item Size :{c.itemsize}")

array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
dimension : 2
Data type : int64
Item Size :8


In [5]:
#3 X3 array of all 9
d=np.full((3,3),9)
print("array :")
print(d)

array :
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [7]:
#Create a 1D array of 10 evenly spaced values between 25 and 125
arr = np.linspace(25, 125, num=10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [9]:
#5. Convert Python list into NumPy array
lst=[10,20,30,40,50,60]
arr=np.array(lst)
print("list to array:")
print(arr)

list to array:
[10 20 30 40 50 60]


In [10]:
# Reverse a 1D NumPy array
d=np.array([11,22,33,44,55,66])
print("original array:")
print(d)
print("reversed array")
print(d[::-1])

original array:
[11 22 33 44 55 66]
reversed array
[66 55 44 33 22 11]


In [13]:
#Create a 4x4x3 array and extract value at second set,
# first row and last column
arr=np.arange(48).reshape(4,4,3)
print("array:")
print(arr)
print("element at second set first row last column :")
print(arr[1,0,2])

array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
element at second set first row last column :
14


In [15]:
#Create a 4x4 and Extract Odd Rows and Even Columns
aa=np.arange(1,17).reshape(4,4)
print("array")
print(aa)
print("odd rows and even columns:")
print(aa[::2,1::2])


array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
odd rows and even columns:
[[ 2  4]
 [10 12]]


In [16]:
#Slice first two rows and first two columns
# of second set from 4x4x3 array
arr = np.arange(48).reshape(4, 4, 3)
print("array")
print(arr)
print("slicing")
print(arr[1,:2:,:2:])

array
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
slicing
[[12 13]
 [15 16]]


In [27]:
#Replace all odd numbers with -1 using for loop
arr=np.array([[15,22,76,54],[11,31,64,82]])
r,c=arr.shape
for i in range(r):
    for j in range(c):
        if arr[i][j]%2!=0:
            arr[i][j]=-1
print(arr)          

[[-1 22 76 54]
 [-1 -1 64 82]]


In [32]:
#Get indices of non-zero elements
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print("\nIndices of Non-Zero Elements:", np.nonzero(arr)[0])


Indices of Non-Zero Elements: [0 2 4 6]


In [34]:
# 12. Arithmetic operations element-wise
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Addition ")
print(arr1+arr2)
print("subtraction ")
print(arr1-arr2)
print("Multiplication ")
print(arr1*arr2)
print("floor Division ")
print(arr1//arr2)
print("exponential ")
print(arr1**arr2)

Addition 
[5 7 9]
subtraction 
[-3 -3 -3]
Multiplication 
[ 4 10 18]
floor Division 
[0 0 0]
exponential 
[  1  32 729]


In [36]:
#dot product
arr1=np.array([15,20,30])
arr2=np.array([5,6,7])
print(arr1)
print(arr2)
print("dot product")
print(np.dot(arr1,arr2))

[15 20 30]
[5 6 7]
dot product
405
